apiVersion: v1
kind: Pod
metadata:
  name: app-with-init
  namespace: test
  labels:
    app: demo-init
spec:
  volumes:
  - name: config-volume
    emptyDir: {}

  initContainers:
  - name: init-config
    image: busybox
    command:
      - sh
      - -c
      - |
        echo "apiVersion: v1\nkind: ConfigMap\nmetadata:\n  name: demo-config" > /config/demo-config.yaml
        echo "Config file created by init container"
    volumeMounts:
    - name: config-volume
      mountPath: /config

  containers:
  - name: main-app
    image: busybox
    command:
      - sh
      - -c
      - |
        echo "Contents of config file:"
        cat /app/config/demo-config.yaml
        sleep 3600
    volumeMounts:
    - name: config-volume
      mountPath: /app/config
